### ISSUE TITLE
I2C pins compilation issue

### ISSUE THREAD

**Issue by aurelj** [nebelgrau77/STM32F051_I2C_weatherstation#1]
Regarding the build issue you show in the README:

```
67 |         let mut bme280 = BME280::new(i2c, bme280_i2c_addr, delay);    
   |                          ^^^^^^^^^^^ the trait `hal::prelude::_embedded_hal_blocking_i2c_Read` is not implemented for `hal::i2c::I2c<hal::stm32::I2C1, hal::gpio::gpioa::PA9<hal::gpio::Alternate<hal::gpio::AF4>>, hal::gpio::gpioa::PA10<hal::gpio::Alternate<hal::gpio::AF4>>>`
   |
   = note: required by `bme280::BME280::<I2C, D>::new`
```

According to the STM32F051 datasheet, the PA9 and PA10 pins in AF4 alternate function are use for capacitive sensing (ie. TSC_G4_IO*), and not for I2C function. That's why those pins are not listed as supported for STM32F051 in https://github.com/stm32-rs/stm32f0xx-hal/blob/master/src/i2c.rs .

You should probably use other pins which do support I2C on the STM32F051 and which are listed in the i2c.rs implementation in the stm32f0xx-hal crate.

**Comment by nebelgrau77** [comment]
Sorry, there's been a misunderstanding, as I pasted the compiler error from a code written for a different MCU. PA9 and PA10 on AF4 are for STM32F030, F051 needs PB8 and PB7 on AF1.
